### ISSUE TITLE
Clean up user storage files after the workshop

### ISSUE THREAD

**Issue by jnywong** [ScienceCore/scipy-2024-climaterisk#10]
Delete data no longer needed from the workshop, especially .netrc files.

**Comment by jnywong** [comment]
Hey @kvenkman can you confirm which home directories you would like to _keep_?

Our protocol for resetting a hub can be found here https://infrastructure.2i2c.org/sre-guide/support/reset-hub/

By default we wipe _all_ home directories, so please indicate the ones you would like to keep.

The following list of current users might prove useful:

![image](https://github.com/ScienceCore/scipy-2024-climaterisk/assets/45105935/285f4371-ec00-4976-bb16-328168b1f55c)

**Comment by kvenkman** [comment]
Hi @jnywong - I think we can safely delete any user directories that were created yesterday. I've asked the users to download any files important to them that were made yesterday, and have pointed them to the repo so that they can continue to use the workflows presented. I'll work on finding an alternative to the `.netrc` plain text password issue.

**Comment by jnywong** [comment]
Task is complete, the remaining directories are 

```
_shared  agoose77  aruliah  dhavide  jmunroe  jnywong  kvenkman  patriloto
```
