### ISSUE TITLE
Rename repository clone on 2i2c hub as scipy-2024-climaterisk

### ISSUE THREAD

**Issue by dhavide** [ScienceCore/scipy-2024-climaterisk#3]
This is a bit picky, but the repository [`scipy-2024-climaterisk`](https://github.com/ScienceCore/scipy-2024-climaterisk) is being cloned into a directory called `scipy-2024-climaterisk.git`. It's not a show-stopper, but it's the kind of thing that will bother me while I'm typing commands at the prompt (yes, I know tab-completion makes it trivial).

@jnywong , can we get that directory renamed without the "`.git`" suffix? I imagine there's a typo in a configuration file somewhere.

![image](https://github.com/ScienceCore/scipy-2024-climaterisk/assets/2997697/0f84ae69-bd06-45ac-8ab5-485293ea7954)

**Comment by jnywong** [comment]
Hey @dhavide ! Thanks for spotting that and opening this issue. I've updated the nbgitpuller link so that the `.git` suffix should no longer appear when launching the hub. 

For those who already have the `scipy-2024-climaterisk.git` repo pulled into your hub, the new nbgitpuller link will pull down the repo again into a new directory without the `.git` extension, so you'll initially have both

```
scipy-2024-climaterisk
scipy-2024-climaterisk.git
```

You might need to push your working changes from your current `.git`-suffixed repo so that they don't get lost, and pull this into the new `scipy-2024-climaterisk` folder. Then you're all set 👍 

I've also taken the liberty to automatically open the `02_Introduction_to_Open_Science.ipynb` notebook. Let me know otherwise if you want that changed.
